Lab 1
MalevychYurii/Malevych-Yurii-IPZ-31 pull request #1
Opened 2023-09-11 09:38 UTC by MalevychYurii

Check pls

2023-09-11 14:29 UTC, vozniuk-lntu requested changes
я бачила цей код
якщо це ти робив тоді обговоримо на парах, якщо ж ні то зроби сам
без зайвих дівів, класів на елементах, БЕМУ і т.д.
це все додасться в процесі потім

2023-09-11 14:29 UTC, vozniuk-lntu commented on src/images/finger_pointer.svg
навіщо це?

2023-09-11 14:29 UTC, vozniuk-lntu commented on index.html
> +    <div class="wrapper">
навіщо обгортка ця?

2023-09-11 14:29 UTC, vozniuk-lntu commented on index.html
> +          <div class="header__right-side-header">
навіщо ця обгортка?

2023-09-11 14:29 UTC, vozniuk-lntu commented on index.html
> +              <button class="solution-for-business__button">
type нема

2023-09-11 14:29 UTC, vozniuk-lntu commented on index.html
> +            <div class="solution-for-business__container">
навіщо обгортка?

2023-09-11 14:29 UTC, vozniuk-lntu commented on index.html
> +        <div class="main__box">
і це нащо?

2023-09-11 14:29 UTC, vozniuk-lntu commented on index.html
> +                <div class="article_item">
ці чотири однотипні штуки списком

2023-09-11 14:29 UTC, vozniuk-lntu commented on index.html
> +                    <img
ширина картинок де?

2023-09-11 14:29 UTC, vozniuk-lntu commented on index.html
> +                  <a href="#">м. Київ, пр-т Лесі Українки, 26</a>
чому адреса посиланням?

2023-09-11 14:29 UTC, vozniuk-lntu commented on index.html
> +            <div class="footer__contact contact">
у футері відсутній adress тег

2023-09-12 06:34 UTC, MalevychYurii commented on src/images/finger_pointer.svg
Робив я. БЕМ для подальшої легшої стилізації css.

2023-09-12 06:34 UTC, MalevychYurii commented on index.html
> +    <div class="wrapper">
Це лише контейнер для зручності, укладаючи блоки в обгортку простіше центрувати, задавати загальну ширину.

2023-09-12 06:36 UTC, MalevychYurii commented on index.html
> +          <div class="header__right-side-header">
Header поділив на 2 частини. Ліву і праву, для легшого розміщення в подальшому.

2023-09-12 06:38 UTC, MalevychYurii commented on index.html
> +              <button class="solution-for-business__button">
Задав type="button"

2023-09-12 06:40 UTC, MalevychYurii commented on index.html
> +            <div class="solution-for-business__container">
main_box видалив. solution-for-business__container - для розділення основних блоків і секцій в мейн

2023-09-12 06:41 UTC, MalevychYurii commented on index.html
> +        <div class="main__box">
main_box видалив.

2023-09-12 06:46 UTC, MalevychYurii commented on index.html
> +                <div class="article_item">
зробив

2023-09-12 06:46 UTC, MalevychYurii commented on index.html
> +                    <img
зробив

2023-09-12 06:48 UTC, MalevychYurii commented on index.html
> +                  <a href="#">м. Київ, пр-т Лесі Українки, 26</a>
виправив

2023-09-12 06:49 UTC, MalevychYurii commented on index.html
> +            <div class="footer__contact contact">
додав

2023-09-13 18:38 UTC, vozniuk-lntu commented on src/images/finger_pointer.svg
окей

2023-09-13 18:39 UTC, vozniuk-lntu commented on index.html
> +    <div class="wrapper">
на мою думку, це зайве
буде видно на стилях чи знадобиться тобі

2023-09-13 18:39 UTC, vozniuk-lntu commented on index.html
> +          <div class="header__right-side-header">
ок

2023-09-13 18:46 UTC, vozniuk-lntu commented
ти шось з шляхами намутив https://i.imgur.com/2gnv7Eq.png
виправляй 
+ нові зауваження

2023-09-13 18:46 UTC, vozniuk-lntu requested changes

2023-09-13 18:46 UTC, vozniuk-lntu commented on index.html
> +                <li class="what-we-do__item" style="width: 270px">
та не на лі
для картинки задаєш ширину, і просто 270 без пх

2023-09-13 18:46 UTC, vozniuk-lntu commented on index.html
> +                <address>
у список не модна зосовувати нічого крім лі
 https://i.imgur.com/wMbtXSR.png
 далі вже у лі йдуть які хоч теги
 ти валідував свій код?

2023-09-20 18:39 UTC, vozniuk-lntu commented on index.html
> +                    <img
та не так
не style
просто width="270"

2023-09-20 18:42 UTC, vozniuk-lntu requested changes
у нас макет зз чотирьох секцій
герой
фічі
що ми робимо
команда
в тебе дві, виправляй

2023-09-20 18:42 UTC, vozniuk-lntu commented on index.html
> +                <img src="/Malevych-Yurii-IPZ-31/src/images/what_we_do/what_we_do1.jpg" alt="img1" style="width: 270" />
просто width="270"
не через style

2023-09-20 18:43 UTC, vozniuk-lntu commented
ти додав обмеження на `мейн `що не модна мержити без апрува?

2023-09-21 06:41 UTC, MalevychYurii commented on index.html
> +                <img src="/Malevych-Yurii-IPZ-31/src/images/what_we_do/what_we_do1.jpg" alt="img1" style="width: 270" />
виправив

2023-09-22 10:41 UTC, vozniuk-lntu approved these changes
шляхи на картинках перед слешем поставити крапку

знайшла деплой ссилку
апрув є, виправиш коменти в другій лабі
зливай в мейн
перевір чи деплоїться
нову гілку з мейн робиш
наступна лаба
https://docs.google.com/document/d/1THT3lT1JlDAHJNTSdngiToexdVmUeLbE/edit?usp=sharing&ouid=104518963218417128491&rtpof=true&sd=true
і скрін як буде виглядати (працюєш суто з шрифтами та кольорами)
https://i.imgur.com/tniDQxh.png

2023-09-25 06:48 UTC, merged