Lab 2
MalevychYurii/Malevych-Yurii-IPZ-31 pull request #2
Opened 2023-09-26 06:53 UTC by MalevychYurii

chekc pls

2023-09-30 08:54 UTC, vozniuk-lntu requested changes
1. додати транзішн (https://developer.mozilla.org/en-US/docs/Web/CSS/transition). Там де hover дописуєш focus.
2. font-style: normal; line-height: normal; font-weight: 400; це на боді і забрати з селекторів

2023-09-30 08:54 UTC, vozniuk-lntu commented on index.html
> +            Замовити послугу
font-family не по макету

2023-09-30 08:54 UTC, vozniuk-lntu commented on index.html
> +              <p class="article-card__subtitle">
колір не по макету

2023-09-30 08:54 UTC, vozniuk-lntu commented on portfolio.html
> +                    <button type="button" class="main__button on_focus">Усі</button>
список кнопок

2023-09-30 08:54 UTC, vozniuk-lntu commented on portfolio.html
> +                <section class="main__filter filter">
достатньо однієї секції

2023-09-30 08:54 UTC, vozniuk-lntu commented on portfolio.html
> +                                <img src="./src/images/filling/filling1.jpg" alt="" class="filling__img">
дефолтна ширина, прописати alt

2023-10-03 18:25 UTC, vozniuk-lntu commented on src/css/style.css
> +  font-family: "Roboto";
додати sans-serif через кому. Це покаже з якого сімейства брати шрифти, якщо не підгрузиться основний

2023-10-03 18:25 UTC, vozniuk-lntu commented on index.html
> +            Замовити послугу
це не виправив

2023-10-03 18:28 UTC, vozniuk-lntu commented on portfolio.html
> +                <section class="main__filter filter">
це не значить тупо видалити, кнопки перемістити в секцію до карточок

2023-10-03 18:28 UTC, vozniuk-lntu commented on portfolio.html
> +                                <img src="./src/images/filling/filling1.jpg" alt="" class="filling__img">
alt="img1" такого не має бути, адекватні описи

2023-10-03 18:32 UTC, vozniuk-lntu requested changes
1. логотип не такий шрийт https://i.imgur.com/PJrpint.png
2. не всюди колір шрифтів 212121 іноді є дефолтний 000000
3. https://i.imgur.com/RniXBIC.png має підсвічуватись синім поточна сторіка
4. тут 500 жирність https://i.imgur.com/WPfKbxb.png
5. це не по макету https://i.imgur.com/QhcmdoM.png
6. обгорни адресу хоч в абзац https://i.imgur.com/u30ZmrJ.png, але тоді це не список. Там по структурі можна `p+a+a` або списко але тоді всередині все посиланнями

ти не виправив всі мої попередні коментарі

2023-10-04 06:57 UTC, MalevychYurii commented
На це раз виправив здається все.

2023-10-10 06:44 UTC, vozniuk-lntu commented on portfolio.html
> +                                <img src="./src/images/filling/filling1.jpg" alt="" class="filling__img">
опис не прописав https://i.imgur.com/J0S93VX.png

2023-10-10 06:45 UTC, vozniuk-lntu commented on src/css/style.css
> +  font-family: "Roboto";
всюди треба прописати, не тільки на одному значенні

2023-10-10 06:51 UTC, vozniuk-lntu requested changes
1. на кнопках не перебив шрифт https://i.imgur.com/F8INzcZ.png
2. ссилку то додав, а куди вона веде? https://i.imgur.com/zXZDluA.png. Обов'язково `rel `атрибут буде, бо ця ссилка на гугл карти має в тебе вести, а це сторонній сайт

ти знову не виправив усі коментарі

2023-10-12 19:20 UTC, vozniuk-lntu approved these changes
в тебе шрифт вішається 14 разів
хоча достатньо 2 (на боді і на логотип) а далі з наслідуванням працюєш

2023-10-23 10:32 UTC, merged