test build first page
MalevychYurii/Malevych-Yurii-IPZ-31 pull request #3
Opened 2023-10-23 12:40 UTC by MalevychYurii

check pls

2023-10-29 19:20 UTC, vozniuk-lntu requested changes
1. Оцьго білого не має бути https://i.imgur.com/D6KIuZY.png. Забури з мейн оце https://i.imgur.com/yWdYhTF.png
2. обнули на боді маржин https://i.imgur.com/WPJOjTS.png
3. по макету там 80 https://i.imgur.com/RGE2cTm.png, де ти взяв 20 зайвих пікселів?
4. оце на хедер контейнер повішай https://i.imgur.com/ugch85S.png, бокові падінги по 15
5. ти обнуляв дефолтні відступи? обнули все бо фігня https://i.imgur.com/f0WTEbi.png
6. і куди ця ссилка веде? https://i.imgur.com/IwJrBwN.png
7. не потрібна обгортка https://i.imgur.com/9XY83X1.png. так було б три елемента в хедер контейнері і добре б флексом стали. Так само і це не треба https://i.imgur.com/0PvCNbn.png. Оці контакти прижимаються до краю автоматичним маржином. Не треба так групувати тупо заради спейс бітвіна
8. навіщо тут обгортка і флекс? https://i.imgur.com/xQMhKsf.png. Елементи блокові, стануть і так один під одний, а центурвати без флекса можна
9. це ПАДІНГ секції https://i.imgur.com/Wtc4hW3.png. А так ти нащадком робиш відступ предка. Це робити не можні і на лекції я демонструвала приклад
10. знову ж таки накинув падінг на нащадка щоб зробити відступ секції https://i.imgur.com/tlOBJKZ.png. А чого це не задати відступом секції?
11. що за відступи по 10 пікселік в секції our-team і section__our-team our-team
12. вони мають в ряд стати https://i.imgur.com/SWUflb9.png
13. отут вже можу бути дів з верхнім і нижнім падінгом https://i.imgur.com/KlX4Vno.png
14. футер не по макету взагалі https://i.imgur.com/kR4KXCv.png
15. забери з кнопок бордери
16. шо це за слонячі відступи?) https://i.imgur.com/pmhsBUS.png. Карточки три в ряд мають бути

2023-10-31 11:14 UTC, MalevychYurii commented
1. Як прижати контактні дані в хедері?

2023-10-31 12:00 UTC, MalevychYurii commented
1. Як прижати контактні дані в хедері?
2. Які відступи по 10 пікселів?
3. Вони в мене і так в ряд стоять :) https://imgur.com/a/lNhv4YV
4. З яких саме кнопок забрати бордери?
5. Карточки в мене так само 3 в ряд https://imgur.com/a/VSDPQpj

2023-11-03 12:11 UTC, vozniuk-lntu commented
1. забери з .header флекс. На .contact__list додай margin-left: auto;
2. ти їх прибрав
3. стали в ряд
4. з всіх
5. тоже вирівнялись

2023-11-03 12:40 UTC, vozniuk-lntu requested changes
1. обнули дефолтні відступи в елементів https://prnt.sc/6ctThvbCZJ-y
2. у портфоліо виправи посилання на логотипі
3. на тег section задаєш верхній і нижній падінг 74пх. Там де вони накладаються обнуляєш непотрібний селектором класу секції. З article-card прибери падінг
4. article-card__item додаєш максимальну ширину в 270пх
5. отут https://prnt.sc/l2GSc7w0L_ZT тільки обин клас .container 
6. тут https://prnt.sc/oUENIwkueEav такий самий клас як в секції, додай слово title
7. our-team__lower прибери верхній падінг і прибрати спейс івентлі
8. тут https://prnt.sc/25u6SFcxHNA4 прибрати всі класи, додати один container
9. в карточці розрбника обгорни заголовок і текст в дів і а дів додай верхній і нижні падінги. Падінги з заголовка і абзаца прибери
10. .footer має мати свої верхні і нижні падінги
11. виправи структуру портфоліо https://prnt.sc/q77A00Cggz0Y
12. в карточці товару в портфоліо виправити відступи в описі

2023-11-03 12:40 UTC, vozniuk-lntu commented on src/css/style.css
> +  padding: 14.4px 15px 14.4px 15px;
верхній 25пх, нижній 24пх і там ще бордер в один піксель

2023-11-03 12:40 UTC, vozniuk-lntu commented on src/css/style.css
> +.container, .filling, .what-we-do, .article-card, .header {
тут .header__container замість .header
.about__container замість .article-card
додай .footer__container
бокові падіги по 15

2023-11-03 12:40 UTC, vozniuk-lntu commented on src/css/nullstyle.css
> +  margin: 0px;
оце на заголовки і абзац теж додай

2023-11-06 20:39 UTC, MalevychYurii commented on src/css/style.css
> +.container, .filling, .what-we-do, .article-card, .header {
1. .header_container ![image](https://github.com/MalevychYurii/Malevych-Yurii-IPZ-31/assets/144584444/70f5bcc1-f934-48c1-87eb-e65afb01da9f)
2. ![image](https://github.com/MalevychYurii/Malevych-Yurii-IPZ-31/assets/144584444/1339c022-0d8e-4e59-bafc-0ea2babaeca5)
3. ![image](https://github.com/MalevychYurii/Malevych-Yurii-IPZ-31/assets/144584444/a9d2816a-d84d-4a97-880c-7dee15bb64ec)

2023-11-06 20:40 UTC, MalevychYurii commented
Ну вроді як все виправив.

2023-11-25 11:16 UTC, vozniuk-lntu requested changes
1. на тег section задаєш верхній і нижній падінг 74пх. тут мало бути 94пх
2. контейнер має бути таким 
.container {
    max-width: 1200px;
    margin: 0px auto;
    padding: 0 15px;
} 
3. мають бути відступи між елементами footer_contact__list list
4. filling_box має мати падінги свої 
5. виправити все з відео https://drive.google.com/file/d/1XC_I80Un2IyBDPxvOFpcpQhF6nwAqjlf/view?usp=sharing

2023-11-25 12:05 UTC, MalevychYurii commented
Дуже дякую за відео, детально і класно пояснено. Все зробив і виправив. svg вже в 4 буду робити

2023-11-25 14:34 UTC, vozniuk-lntu approved these changes
1. https://i.imgur.com/dmzs1ym.png колір не по макету
це все до хедера, покроково
1. .header__container прибери `justify-content: space-between;
    gap: 93px;`
2. на header__logo правий маржин 93пх
3. list__item прибери падінг
4. contact__list гап додай

я певно на хедер уваги не звернула
це апрув

2023-11-25 20:03 UTC, merged